### ISSUE TITLE
Panic in Bay Trail-M (Celeron N2830): Trying to add overlapping vm fictitious ranges

### ISSUE THREAD

**Issue by Juanitou** [FreeBSDDesktop/freebsd-base-graphics#124]
With 945ea51 and the latest packages, I'm getting an instant panic when starting X, without a xorg.conf:

Trying to add overlapping vm fictitious ranges:
[0x80000000:0x90000000] and [0x80000000:0x90000000]

This is on a Bay Trail-M (Celeron N2830) which was not working well before, but at least did not panic.

I have a core, but don't know what to do with it.

**Comment by Juanitou** [comment]
More details:
![p1020218](https://cloud.githubusercontent.com/assets/807463/23330392/15bad5e2-fb4d-11e6-87f5-ce5b00c013ac.JPG)

**Comment by markjdb** [comment]
Hi,

Could you please retest on the latest drm-next? I've pushed a revert which ought to address this.

**Comment by Juanitou** [comment]
Hi Mark.

Yes, the panic is gone. Video is still not working on this computer, but that is another issue.

Thank you all for this great work!
